In [10]:
using DifferentialEquations
using ParameterizedFunctions

type SSNParam
    w
    h
    τ
    k
    n
end

ReLU(x) = x < 0.0 ? 0.0 : x

function ssn_ode(t, u, param, du)
    w = param.w
    h = param.h
    τ = param.τ
    n = param.n
    k = param.k
    du .= (- u .+ k .* ReLU.(w * u .+ h).^n) ./ τ
end

INFO: Precompiling module DifferentialEquations.
This may mean module Compat does not support precompilation but is imported by a module that does.
ERROR: LoadError: Declaring __precompile__(false) is not allowed in files that are being precompiled.
Stacktrace:
 [1] _require(::Symbol) at ./loading.jl:455
 [2] require(::Symbol) at ./loading.jl:405
 [3] include_from_node1(::String) at ./loading.jl:576
 [4] include(::String) at ./sysimg.jl:14
 [5] anonymous at ./<missing>:2
while loading /Users/jantinebroek/.julia/v0.6/MacroTools/src/MacroTools.jl, in expression starting on line 4
ERROR: LoadError: Failed to precompile MacroTools to /Users/jantinebroek/.julia/lib/v0.6/MacroTools.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:710
 [2] _require(::Symbol) at ./loading.jl:463
 [3] require(::Symbol) at ./loading.jl:405
 [4] include_from_node1(::String) at ./loading.jl:576
 [5] include(::String) at ./sysimg.jl:14
 [6] anonymous at ./<missing>:2
while loading /Users/jantinebroek/.ju

LoadError: Failed to precompile DifferentialEquations to /Users/jantinebroek/.julia/lib/v0.6/DifferentialEquations.ji.

In [2]:
w = [1 -3
     1 -1]

2×2 Array{Int64,2}:
 1  -3
 1  -1

In [3]:
τ = [1, 0.1]

2-element Array{Float64,1}:
 1.0
 0.1

In [4]:
h = [0.1, 0.1]

2-element Array{Float64,1}:
 0.1
 0.1

In [5]:
ssn = ParameterizedFunction(ssn_ode, SSNParam(
    w,
    τ,
    h,
    0.01,  # k
    2.2,   # n
))

LoadError: UndefVarError: ParameterizedFunction not defined

In [6]:
ode = ODEProblem(ssn, ones(2), (0.0, 5.0))

LoadError: UndefVarError: ODEProblem not defined

In [7]:
sol = solve(ode);

LoadError: UndefVarError: solve not defined

In [8]:
using Plots

LoadError: ArgumentError: Module Plots not found in current path.
Run `Pkg.add("Plots")` to install the Plots package.

In [9]:
plot(sol, vars=[1, 2])

LoadError: UndefVarError: plot not defined